rabbitmq/amqp091-go

channel.go, connection_test.go
Hey Guys, this is an old PR from streadway, and since we have this "official" fork, I'd still think is a good idea (and I need this haha)
I needed to access the Channel state on a project that I'm participating in. So, I just made the "closed" field public on channel.go in the same way as it is on connection.go. Nothing too fancy, but I think it is important to get the actual status of the channel.
Something that we have on RabbitMQ's client on Python (pika) and .Net (RabbitMQ) and I missed here.
Hope this helps,
Best regards. 
[Original Pull Request](https://github.com/streadway/amqp/pull/486)
=> Exporting Channel State

connection.go
This pull request resolves https://github.com/streadway/amqp/issues/493
As per https://www.rabbitmq.com/heartbeats.html#heartbeats-interval
>Heartbeat frames are sent about every heartbeat timeout / 2 seconds. This value is sometimes referred to as the heartbeat interval. After two missed heartbeats, the peer is considered to be unreachable. Different clients manifest this differently but the TCP connection will be closed. When a client detects that RabbitMQ node is unreachable due to a heartbeat, it needs to re-connect.
It is important to not confuse the timeout value with the interval one. RabbitMQ configuration exposes the timeout value, so do the officially supported client libraries. However some clients might expose the interval, potentially causing confusion.
[I did my best to …
=> Heartbeat interval should be timeout/2

.github/workflows/pr.yml, .travis.yml
I've made the following modifications.
* add mutiple go-version 1.16 and 1.17 to `pr.yml`. (I refered to `Supported Go Versions` on README. )
* add go-version 1.17 to `travis.yml`.
* fix indent.
=> add test go version 1.16.x and 1.17.x

README.md
Add a link to Go API references from https://pkg.go.dev.
Preview available here: https://github.com/benmoss/amqp091-go/blob/add-godoc-link/README.md 😄
=> Add a link to pkg.go.dev API docs

auth.go, client_test.go
I'm copying and pasting from streadway/amqp#515, since I guess this fork is more actively maintained :)
Fixes #15.
The current AMQPLAIN implementation does not work with `rabbitmq` out-of-the-box.
I could not find an official reference for that authentication mechanism. Looking at other implementations ([rust](https://github.com/CleverCloud/amq-protocol/blob/master/protocol/src/auth.rs#L45), [python](https://github.com/celery/py-amqp/blob/7300741f9fc202083e87abd10e1cb38c28efad92/amqp/sasl.py#L48)) it seems that AMQPLAIN uses an AMQP table (`LOGIN` and `PASSWORD` fields), omitting the table length.
=>  Fix AMQPLAIN authentication mechanism

connection.go
The documentation for `NotifyClose()` differs between [Channel](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Channel.NotifyClose):
> The chan provided will be closed when the Channel is closed and on a graceful close, no error will be sent.
and [Connection](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Connection.NotifyClose):
> On normal shutdowns, the chan will be closed.
The latter wording suggests that on abnormal shutdowns the chan will remain open, with two expected features:
* A non-blocking chan could be registered and the error notification would still be available to the application; and
* a new Connection could pass that same chan to `NotifyClose()` so an existing select statement need not update the chan it monitors.
In fact the logic for maintaining close notifiers …
=> connection: clarify documented behavior of NotifyClose

confirms.go, confirms_test.go
Confirms come in asynchronously and are put onto the confirmation channel. This will block until the consumer receives on that channel. If a user is alternating publishing and consuming acknowledgements, an acknowledgement that comes in during a publish will cause a deadlock.
Fixes #10
=> Fix deadlock between publishing and receiving confirms

channel.go, client_test.go, confirms.go, confirms_test.go, types.go
Adds a new method, PublishAndAwaitConfirm, to channels which allows users to publish a message and wait on its confirmation.
There are two problems with the existing mechanisms, [NotifyPublish](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Channel.NotifyPublish) and [NotifyConfirm](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Channel.NotifyConfirm). The first is that they both only expose confirmations to the user _in-order_, making it impossible to wait for a single confirmation without also waiting for every previous confirmation. The second is that the way they relay the confirmation back to the user is difficult to correlate to the published message. They expose the delivery tag through the [Confirmation struct](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Confirmation), …
=> Expose a method to enable out-of-order Publisher Confirms

example_client_test.go
The `[example_client_test.go](./example_client_test.go)` is using two types of logging mechanism:
https://github.com/rabbitmq/amqp091-go/blob/21ccfdea51148da4de39d35975fdd44480e979e2/example_client_test.go#L89
and
https://github.com/rabbitmq/amqp091-go/blob/21ccfdea51148da4de39d35975fdd44480e979e2/example_client_test.go#L217
This Pull Request is changing the logging behavior to only use the logging instance inside the session struct
=> Client example: Use instance logger instead of global logger

example_client_test.go
The client example uses a variable called `name`.
Reading through example, questions will arise "What name is it?".
Especially in the context of AMQP/RabbitMQ this can be the Exchange name, the queue name, the routing key name, the consumer name, etc.
To make the usage clear and explicit, we rename `name` to `queueName`.
=> Example client: Rename `name` to `queueName` to make the usage clear and explicit

example_client_test.go
The example client names its functionality to consume messages from a queue `Stream()`.
With one of the latest versions of RabbitMQ, [RabbitMQ Streams](https://www.rabbitmq.com/streams.html) have been introduced.
From what I can see, the API is also using `Consume`, but requires custom arguments like `x-queue-type`. In the example client, these arguments are not used so far.
To avoid confusion between "simple" consuming and the new Streaming functionality, this PR renames `Stream()` to `Consume()`.
=> Example client: Rename Stream() to Consume()  to avoid confusion with RabbitMQ streams

confirms.go, confirms_test.go, integration_test.go
This PR improves the changes proposed in #44 originally made by @shifengbin
Changes:
- Fixed deadlock that occurs with DeferredConfirmations when connection is reset
- Made the fix's code more consistent with the other methods in the file
- Added some documentation for `Wait()` and other internal methods
- Added unit test for `deferredConfirmations.Close()`
- Added integration test to confirm that `.Wait()` will return `ack: false` when connection is closed (as suggested by @DanielePalaia )
The newly added unit & integration tests both passed consistently when I ran them
This problem is also mentioned in #46
=> Fix deadlock on DeferredConfirmations

connection.go
Add the client platform.
Per conversation with @Zerpet  and @DanielePalaia
=> Remove the old link product

integration_test.go
Creating an integration test for issue11
=> adding integration test for issue 11

.github/workflows/tests.yml, Makefile, connection.go, connection_test.go, reconnect_test.go
When a message was sent and it's response was received while the
connection was closed or an error happened, the reader go-routine could
get stuck and be leaked.
The reader go routine tries to send a received message to the unbuffered
c.rpc channel via the dispatch0() and dispatchN() methods.
The call() method reads from the rpc channel.
If an error happened while the dispatch method sends a message to the
rpc channel, the call() method could terminate because it read an error
from c.errors or because c.errors was closed.
To prevent the scenario:
- the reader go-routine now closes c.rpc when it terminates,
- The call() method, reads from c.rpc until a message was received or it
is closed. When c.rpc is closed, it reads an error from c.errors or
wait until c.errors is closed.
When it reads …
=> connection: fix: reader go-routine is leaked on connection close

.github/workflows/golangci-lint.yml, .golangci.yml, CONTRIBUTING.md, Makefile
Add a github action workflow to run golangci-lint.
golangci-lint is configured to only show new issues from PRs.
When all existing issues in the main branch are fixed (or excluded),
only-new-issues could be set to false.
=> ci: run golangci-lint

channel.go
The channel recv*() methods and transition() were always returning a nil error.
These methods are changed to return nothing instead of always nil.
golangci-lint was complaining that the code ignored the returned error by channel.recv().
This change gets rid of the warning and simplifies the code.
=> channel: return nothing instead of always a nil-error in receive methods

.github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/tests.yml, channel.go, client_test.go, connection.go, connection_test.go, examples_test.go, integration_test.go, read.go, reconnect_test.go, tls_test.go, types.go, uri.go, write.go
Start by removing some dead code.
@fho I have added you as a collaborator on my fork. Please feel free to push to this branch.
=> Fix lint errors

Makefile, channel.go, client_test.go, connection.go, connection_test.go, integration_test.go, log.go, tls_test.go
=> Add logging

channel.go, connection.go, integration_test.go
=> Do not skip flaky test in CI

connection.go
The documentation for `connection.NotifyClose()` was mentioning a channel. This is incorrect, it should mention a connection, since this is the connection module.
This fixes #89
=> Update connection documentation

connection.go, integration_test.go
Hi, 
In the clustered RabbitMQ installation it is often necessary to get the remote node's IP address to be able to determine to which node exactly you are connected to.
Having that in mind, I've added `conn.RemoteAddr()` method which behaves similar to `conn.LocalAddr()` but returns remote peer IP address:port instead of local one.
Thank you and have a good day!
=> Added function to get the remote peer's IP address (conn.RemoteAddr())

connection.go, uri.go, uri_test.go
Add support for `cacertfile`, `certfile`, `keyfile`, `server_name_indication` from https://www.rabbitmq.com/uri-query-parameters.html
* If `cacertfile` is not provided, system CA certificates will be used.
* Mutual TLS (client auth) will be enabled only in case `keyfile` AND `certfile` provided.
* If `Config.TLSClientConfig` is set, TLS parameters from URI will be ignored.
=> Add build TLS config from URI

confirms.go, confirms_test.go, types.go
When doing more testing, I found one race condition is now possible with the PR #96.
This add test to detect the race condition and add basic solution to prevent to happen.
Sorry for this little possible bug.
One better way would be to use atomic with a uint32 as a bool but that imply potentially a lot of code change
=> fix race condition with context close and confirm at the same time on DeferredConfirmation.

_examples/simple-consumer/consumer.go, _examples/simple-producer/producer.go, connection.go, connection_test.go, examples_test.go, types.go
RabbitMQ reads the connection property "connection_name" from the client and displays the value in the Management UI. This is convenient for debugging and locating specific client connections, and correlating a connection to an app.
See #105 for more details.
=> Add convenience function to set connection name

example_client_test.go
The example function `func Example_consume()` shows how to write a consumer with reconnection support.
This PR also changes the notification channels to be buffered with capacity of 1. This is important to avoid potential deadlocks during an abnormal disconnection. See #32 and #18 for more details.
Both example functions now have a context with timeout, so that they don't run forever. The QoS of 1 is set to slowdown the consumption; this is helpful to test the reconnection capabilities, by giving enough time to close the connection via the Management UI (or any other means).
Fixes #40
=> Add an example of reliable consumer

channel.go, spec/amqp0-9-1.stripped.extended.xml, spec/gen.go, spec091.go
Adding missing constant 302 for no-route error.
The spec says that `basic.recover` should be async, but this breaks our
test `TestIntegrationRecoverNotImplemented()`. RabbitMQ has deprecated
this method and it will be removed in a future release. This commit also
adds a deprecation notice to `channel.Recover()`.
=> Update AMQP Spec

README.md
The go tutorial has been updated to use rabbitmq/amqp091-go
https://github.com/rabbitmq/rabbitmq-tutorials/commit/52ca462906a6cd10e387e39074cee468f6bd2b47
=> Remove warning on RabbitMQ tutorials in go

connection.go, examples_test.go
This method is in the AMQP 0.9.1 spec and it is supported by RabbitMQ.
This is useful when the secret used in the connection has an expiry, as
it allows the applications to renew the secret without the hassle of
closing-reconnecting consumers/producers.
=> Add support for connection.update-secret

_examples/pubsub/pubsub.go, _examples/simple-producer/producer.go
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>
=> use PublishWithContext instead of Publish

example_client_test.go
The example was "giving up" on publish confirmation after the
resendDelay. This is not correct because the library will keep track of
this confirmation, and it will try to deliver the confirmation. By
giving up, we are may leave confirmations un-received in the
confirmation channel, which will cause a deadlock during the shut down
sequence in Channel.Close.
We should not give up on the confirmation and simply wait.
Fixes #122
=> Fix example client to avoid deadlock in Close

types.go
Defining a constant for the default exchange is clearer than using an empty string `""`.
=> Add constant for default exchange

channel.go, connection.go
As per issue https://github.com/rabbitmq/amqp091-go/issues/141
Improve the performance of Channel sendOpen method by adding an sendUnflushed method to Connection that allows us to use the write buffer more efficiently by writing all the Frames of the message and *then* flushing the buffer rather than flushing each Frame. This significantly improves the performance of basicPublish for small messages where the bulk of the CPU load tends towards Syscall so with small messages we might have a Syscall per message vice per Frame.
=> Fix inefficient use of buffers that reduces the potential throughput of basicPublish

channel.go, confirms.go, confirms_test.go, types.go
This change removes embedded `context.Context` (which is generally an anti-pattern) from `DeferredConfirmation`. Instead, we use a simple channel to wait for ack/nack status. This approach is more flexible since it can be combined with timers, tickers, other contexts and channels in general using `select{}` statements and there is no overhead from context cancellation setup.
Note that #96 introduced a behavior where `Wait` would unblock and return false once the context passed to `Publish` expires. This commit reverts this (arguably breaking) behavior in favor of `WaitContext` function.
=> Do not embed context in DeferredConfirmation

.ci/versions.json, .github/workflows/tests.yml, Makefile, _examples/simple-consumer/consumer.go, _examples/simple-producer/producer.go, channel.go, connection.go, doc.go, integration_test.go, read.go, types.go, uri.go, write.go
Also bump Windows dep versions
=> Ensure code is formatted

README.md
Removes outdated information in README as requested and according to https://github.com/rabbitmq/amqp091-go/issues/154.
=> Remove outdated information from README

change_version.sh, connection.go, integration_test.go, read.go
This PR fixes linter warnings, reported in the Goland IDE. The warnings in
question:
- Unreachable code
- Variable names using snake_case instead of CamelCase
- Unused parameters
- Redundant parenthesis
- Shell-bang was not set correctly
Any code after `t.Fatalf` is not executed, because this function stops
execution.
=> Fix linter warnings

channel.go, connection.go, write.go
=> Ensure flush happens and correctly lock connection for a series of unflushed writes

Makefile
Simplified version of 'stop-rabbitmq-server'. There is no need to figure
out the container ID, because `docker stop` supports container names.
Container name can now be customised.
Edit: did not assign a milestone because this change is for developers of the library
=> Update Makefile targets related to RabbitMQ

.github/workflows/tests.yml
I added go version 1.20 to testing workflow.
=> adding go 1.20 to tests

Makefile, connection.go
- Lock allocator assignment in openComplete
- Add a critical section in openTune
In #170, it was reported a data race in `Connection.Open`. The situation
described is an edge case, where the connection reader (responsible for reading
data sent from the server/wire) initiates the shutdown sequence in
`Connection.shutdown` before `Connection.Open` completes. This creates a data
race for `Connection.allocator` and `Connection.Config.ChannelMax` fields.
The shutdown function is already protected by the `Connection` struct mutex. The
access from `Open` stack calls is not protected. This PR adds two new, as small
as possible, critical sections protected by the struct mutex during `Open`.
It is quite challenging to add a reliable test for this edge case, even with a
server fake, since we have to …
=> Fix racing in Open

connection.go
In observed the following panic in the wild:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x54 pc=0x104cf3c]
goroutine 144 [running]:
github.com/rabbitmq/amqp091-go.(*Channel).setClosed(...)
/home/runner/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.5.0/channel.go:94
github.com/rabbitmq/amqp091-go.updateChannel(...)
/home/runner/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.5.0/types.go:329
github.com/rabbitmq/amqp091-go.(*Connection).dispatchN(0xc000b2ea00, {0x1d5c150, 0xc00096f1b8?})
/home/runner/go/pkg/mod/github.com/rabbitmq/amqp091-go@v1.5.0/connection.go:539 +0xbc
github.com/rabbitmq/amqp091-go.(*Connection).demux(0xc00039cf28?, {0x1d5c150, 0xc00096f1b8}) …
```
=> Check if channel is nil before updating it

client_test.go, connection.go
Follow up to #171
cc @Zerpet
cc @jxsl13 since it may be interesting
=> Set channels and allocator to nil in shutdown

consumers.go
Fixes https://github.com/rabbitmq/amqp091-go/issues/179
=> Fix memory leaks

.github/workflows/tests.yml, CONTRIBUTING.md, Makefile, connection.go, connection_test.go, integration_test.go, types.go
- Add CloseDeadline function to Connection
- Remove unused function in integration tests
- Updated contribution guidelines
Fixes #178
During a [memory alarm][rmq-memory-alarm], RabbitMQ will block publisher connections. This means that RabbitMQ will stop reading from the connection socket. In this case, any further attempts from the client using this connection will be blocked on I/O. For example, a connection close request, will block in I/O, and the client application will be blocked.
Other clients, like Java or C#, use a timeout when closing a connection, and return an exception if the connection is not closed within the timeout. Those clients also do connection recovery, but that's outside of the scope of this client (See README anti-goals).
This client now also provides a …
=> Add a CloseDeadline function to Connection

channel.go, confirms.go, confirms_test.go
=> Fix race condition on confirms

channel.go, integration_test.go
This is a reference implementation for https://github.com/rabbitmq/amqp091-go/issues/124#issuecomment-1547138079.
=> Add Channel.ConsumeWithContext to be able to cancel delivering

examples_test.go, tls_test.go, types.go
Documentation to queue argument constants was missing links to the
constant themselves. Go Doc allows to link to a specific symbol using
squared brackets.
Added as well a constant for SAC in CQ and QQ.
Fixes #201
=> Constant for consumer timeout queue argument

integration_test.go
I found an integration test of #192 failed on windows-latest (1.20). I guess it's a timing issue?
```
=== RUN   TestIntegrationConsumeCancelWithContext
integration_test.go:857: Timeout on Close
--- FAIL: TestIntegrationConsumeCancelWithContext (0.27s)
```
https://github.com/rabbitmq/amqp091-go/actions/runs/5322251884/jobs/9638444129
=> Fix to increase timeout milliseconds since it's too tight

client_test.go, integration_test.go, reconnect_test.go
- Use the recommended PublishWithContext version.
- Made some minor syntax corrections to some comments.
- Left a TODO to remove Recover test
=> Stop using deprecated Publish function

.ci/versions.json, .github/workflows/golangci-lint.yml, .github/workflows/tests.yml
Golang 1.19 is no longer supported.
=> Bump versions

allocator.go, allocator_test.go, channel.go, connection.go
Closes https://github.com/rabbitmq/amqp091-go/issues/222
=> Closes 222

types.go
So this one got me good on a really nasty bug from my side. I was using the pkg to publish big batches of messages to a queue. When reading the source code it was not clear to me the value was used as milliseconds. I assumed wrongly if the value is `0` the message will not expire. I assumed this because `0` would be the nil value for a go int. This assumption was painfully wrong - which lead to all messages not immediately retrieved by the consumer to get rightfully deleted. I wanted to spare others from the same mistake.
I am perfectly aware the rabbit mq documentation states the usage here: https://www.rabbitmq.com/ttl.html#per-message-ttl-in-publishers
But I think a little more documentation in the code and some clarification can prevent others from making the same mistake. I also …
=> Documenting Publishing.Expiration usage

channel.go, integration_test.go
The `confirms` type uses the `publishedMut` to guard access to the `published` field:
https://github.com/rabbitmq/amqp091-go/blob/a6fa7f7d76ecb00f1f46d42d02adfe0454c5514f/confirms.go#L43-L47
https://github.com/rabbitmq/amqp091-go/blob/a6fa7f7d76ecb00f1f46d42d02adfe0454c5514f/confirms.go#L53-L56
etc.
However, the `Channel` type uses the mutex `m` (on the `confirms` type) instead:
https://github.com/rabbitmq/amqp091-go/blob/a6fa7f7d76ecb00f1f46d42d02adfe0454c5514f/channel.go#L1829-L1832
This can lead to race if the `GetNextPublishSeqNo` function is used while other functions on the `confirms` type is used concurrently.
=> Use correct mutex to guard confirms.published

auth_test.go, types_test.go
This PR aims to add two simple tests:
- auth.go
- types.go
The main goal is to increase the code coverage on two opportunities I saw taking into consideration that doesn't add noises or need to change on the main code, only tests.
=> Increasing the code coverage

_examples/pubsub/pubsub.go
Related to https://github.com/rabbitmq/amqp091-go/issues/249
=> Example fix

.github/workflows/codeql-analysis.yml, .github/workflows/golangci-lint.yml, .github/workflows/tests.yml, connection.go, integration_test.go
https://github.com/rabbitmq/amqp091-go/security/code-scanning/1
=> Address CodeQL warning

.ci/versions.json, connection.go, types.go, uri.go, uri_test.go
[RabbitMQ URI Query Parameters](https://www.rabbitmq.com/docs/uri-query-parameters) specifies several parameters that are used in this library, but not supported in URIs.
This commit adds support for the following parameters:
`auth_mechanism`
`heartbeat`
`connection_timeout`
`channel_max`
=> Add support for additional AMQP URI query parameters

tls_test.go, uri.go, uri_test.go
The string method was not including possible query parameters, namely,
TLS parameters. This fix brings our URI implementation in accordance
with the standard libary net/url, which does include query parameters in
their String() function.
=> Fix string function of URI

_examples/producer/producer.go, _examples/pubsub/pubsub.go, channel.go, doc.go
The context was not honoured in any of the *WithContext functions. This
is confusing, and arguably broken. However, we cannot immediately fix
the context-support situation due to https://github.com/rabbitmq/amqp091-go/issues/124#issuecomment-1578529925
This commit undeprecates the non-context variants of publish, and
documents that both variants are equivalent. The example now favours the
non-context variants.
Fixes #195
=> Undeprecate non-context publish functions

_examples/client/client.go, _examples/consumer/consumer.go, example_client_test.go
Some users rely on this example as a starting point to their
applications. This commit fixes a data race that could cause issues in
any code that relied on the example as base.
Fixes #72
=> Fix data race in example

_examples/client/client.go, _examples/producer/producer.go, _examples/pubsub/pubsub.go, allocator_test.go, auth.go, channel.go, client_test.go, connection.go, connection_test.go, consumers.go, delivery.go, example_client_test.go, examples_test.go, integration_test.go, log.go, read.go, spec/gen.go, spec091.go, tls_test.go, types_test.go, uri.go, write.go
some commits moved from PR #265
=> Small fixes and refactors

connection.go
This fixes #291.
It is tribal knowledge that channels should not be used accessed by
multiple goroutines. Adding this warning to the function documentation
should avoid further issues like #291.
=> Add warning about concurrency with Channels

_examples/client/client.go
Methods UnsafePush and Consume returns errNotConnected in the same conditions
=> Return existing error instead of creating new for the same purpose

integration_test.go
Write test that demonstrates issue with using `Qos` and async workers.
Fixes #296
=> Investigate GH-296
